version: 2
jobs:
  build:
    docker:
      - image: gcr.io/rxjs-fiddle/ci/gcloud:0.0.7
        auth:
          username: _json_key
          password: ${GCLOUD_SERVICE_KEY}

    steps:
      - checkout

      - run: echo ${GCLOUD_SERVICE_KEY} > keyfile.json
      - run: gcloud auth activate-service-account ${GCLOUD_SERVICE_NAME} --key-file keyfile.json
      - run: gcloud container clusters get-credentials standard-cluster-1 --zone us-central1-a --project rxjs-fiddle
      - run: kubeless function ls
