version: 2
jobs:
  build:
    docker:
      - image: gcr.io/rxjs-fiddle/ci/gcloud:0.0.7
        auth:
          username: _json_key
          password: ${GCLOUD_SERVICE_KEY}

    steps:
      - checkout

      - run: gcloud version
