version: 2.1
jobs:
  Bump Git Tag:
    docker:
      - image: gcr.io/rxjs-fiddle/ci/gitversion:0.0.8
        auth:
          username: _json_key
          password: ${GCLOUD_SERVICE_KEY}

    steps:
      - add_ssh_keys:
          fingerprints:
            - "19:86:7d:89:ad:2b:24:95:d5:fe:59:1a:92:46:4f:02"
      - checkout
      - run: gitversion bump auto
      - run: git push origin --tags
  Deploy:
    parameters:
      env:
        type: string
      version:
        type: string

    environment:
      RXJS_FIDDLE_ENV: << parameters.env >>
      RXJS_FIDDLE_VERSION: << parameters.version >>

    docker:
      - image: gcr.io/rxjs-fiddle/ci/gcloud:0.0.11
        auth:
          username: _json_key
          password: ${GCLOUD_SERVICE_KEY}

    steps:
      - checkout
      - run: echo ${GCLOUD_SERVICE_KEY} > keyfile.json
      - run: gcloud auth activate-service-account ${GCLOUD_SERVICE_NAME} --key-file keyfile.json
      - run: gcloud container clusters get-credentials rxjs-fiddle-cluster --zone us-central1-a --project rxjs-fiddle
      - run: env
      - run: kubectl apply -f k8s/

workflows:
  Deploy to Staging for Commits to Master:
    jobs:
      - Deploy:
          env: staging
          version: ${CIRCLE_SHA1}
          filters:
            branches:
              only: master
      - hold:
          type: approval
          requires:
            - Deploy
          filters:
            branches:
              only: master
      - Bump Git Tag:
          requires:
            - hold
          filters:
            branches:
              only: master

  Deploy to Production for Tags:
    jobs:
      - Deploy:
          env: default
          version: ${CIRCLE_TAG}
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
