apiVersion: apps/v1
kind: Deployment
metadata:
  name: rxjs-fiddle-backend-deployment
  labels:
    app: rxjs-fiddle-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rxjs-fiddle-backend
  template:
    metadata:
      labels:
        app: rxjs-fiddle-backend
    spec:
      containers:
        - name: rxjs-fiddle-backend
          image: gcr.io/rxjs-fiddle/backend:${IMAGE_TAG}
          ports:
            - containerPort: 8080
          env:
            - name: ENVIRONMENT_NAME
              value: ${ENVIRONMENT_NAME}
            - name: API_VERSION
              value: ${API_VERSION}
            - name: SIGNALFX_AGENT_HOST
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
      imagePullSecrets:
        - name: gcr-auth
