apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
namespace: rxjs-fiddle-stg
nameSuffix: -stg
configMapGenerator:
  - name: rxjs-fiddle-backend-env-config
    literals:
      - ENVIRONMENT_NAME=staging
      - API_VERSION=latest
resources:
  - image-pull-secret.yaml
  - image-sync.yaml
patchesStrategicMerge:
  - set-image-pull-secret.yaml
