apiVersion: apps/v1
kind: Deployment
metadata:
  name: rxjs-fiddle-backend-deployment
  labels:
    app: rxjs-fiddle-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rxjs-fiddle-backend
  template:
    metadata:
      labels:
        app: rxjs-fiddle-backend
    spec:
      containers:
        - name: rxjs-fiddle-backend
          image: gcr.io/rxjs-fiddle/backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SIGNALFX_AGENT_HOST
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
          envFrom:
            - configMapRef:
                name: rxjs-fiddle-backend-env-config
